title: antennaConfig
type: object
description: Represents an RFID reader antenna configuration.
properties:
  Antennas:
    type: array
    description: The antennas connected to the reader.
    items:
      type: object
      properties:
        id:
          type: string
          description: The antenna ID.
          example: '0'
        transmitPower:
          type: string
          description: The configured antenna transmit power level.
          example: '10'
      required:
        - id
        - transmitPower
required:
  - Antennas
