title: cloudConfig
type: object
description: Represents an RFID reader cloud configuration.
properties:
  hostname:
    type: string
    description: The cloud hostname of the reader.
    example: RIFID14E3D4F
  commSettings:
    type: object
    properties:
      edgeMicroGatewayAddress:
        type: string
        description: The IP address of the edge micro gateway.
        example: 123.456.7.8
      proxyAddress:
        type: string
        description: The IP address for the proxy.
        example: 234.567.8.9
  location:
    $ref: ../location/geolocation.v1.yaml
