title: antennaConfig
type: object
description: Represents an RFID reader antenna configuration.
properties:
  Antennas:
    type: array
    description: The antennas connected to the reader.
    items:
      $ref: ./antenna.v1.yaml
required:
  - Antennas
