title: antennaConfig
type: object
description: Represents an RFID reader antenna configuration.
properties:
  Antennas:
    type: array
    description: The antennas connected to the reader.
    items:
      type: object
      properties:
        id:
          type: string
          description: The antenna ID.
          example: '0'
        transmitPower:
          type: number
          description: The configured antenna transmit power level.
          example: '10'
          minimum: 10
          maximum: 30
        name:
          type: string
          description: The name of the reader
        session:
          type: integer
          default: 0
          example: '0'
          minimum: 0
          maximum: 3
          description: 'The session configuration to apply (0, 1, 2, 3)'
      required:
        - id
        - transmitPower
        - name
        - session
required:
  - Antennas
