title: cloudConfig
type: object
description: Represents an RFID reader cloud configuration.
properties:
  hostname:
    type: string
    description: The cloud hostname of the reader.
    example: RIFID14E3D4F
  commSettings:
    type: object
    description: The communication settings for the reader.
    properties:
      edgeMicroGatewayAddress:
        type: string
        description: The IP address of the edge micro gateway.
        example: 123.456.7.8
      proxyAddress:
        type: string
        description: The IP address for the proxy.
        example: 234.567.8.9
  location:
    oneOf:
      - $ref: ../location/geolocation.v1.yaml
      - $ref: ../location/indoorlocation.v1.yaml
    description: The location of the reader.
  state:
    type: string
    enum:
      - a
      - b
    example: a
    description: The EPC Gen 2 state setting for the reader.
  memory:
    type: array
    default: epc
    description: The memory bank(s) to send to the cloud.
    enum:
      - epc
      - user
      - tid
    example: epc
    items:
      type: string
required:
  - hostname
  - state
  - memory
