title: readerConfig
type: object
properties:
  Config:
    type: object
    properties:
      AppVersion:
        type: object
        properties:
          major:
            type: string
            example: ABC123
          minor:
            type: string
            example: ABC123
          build:
            type: string
            example: ABC123
          maintenance:
            type: string
            example: ABC123
      CommConfig:
        type: object
        properties:
          EnabledStacks:
            type: string
            example: ABC123
          DisableRAPktProcessing:
            type: string
            example: ABC123
          EnableDHCPv6:
            type: string
            example: ABC123
          IPv6StaticIPAddr:
            type: string
            example: ABC123
          IPv6SubnetMask:
            type: string
            example: ABC123
          IPv6StaticGateway:
            type: string
            example: ABC123
          IPv6DNSIP:
            type: string
            example: ABC123
          DHCP:
            type: string
            example: ABC123
          IPAddr:
            type: string
            example: ABC123
          Mask:
            type: string
            example: ABC123
          Gateway:
            type: string
            example: ABC123
          DNS:
            type: string
            example: ABC123
          HttpRunning:
            type: string
            example: ABC123
          TelnetActive:
            type: string
            example: ABC123
          FtpActive:
            type: string
            example: ABC123
          usbMode:
            type: string
            example: ABC123
          WatchdogEnabled:
            type: string
            example: ABC123
          SerialConTimeout:
            type: string
            example: ABC123
          SNTP:
            type: string
            example: ABC123
          sntpHostDisplayMode:
            type: string
            example: ABC123
          llrpClientMode:
            type: string
            example: ABC123
          llrpSecureMode:
            type: string
            example: ABC123
          llrpSecureModeValidatePeer:
            type: string
            example: ABC123
          llrpPort:
            type: string
            example: ABC123
          llrpHostIP:
            type: string
            example: ABC123
          allowllrpConnOverride:
            type: string
            example: ABC123
      Bluetooth:
        type: object
        properties:
          discoverable:
            type: string
            example: ABC123
          pairable:
            type: string
            example: ABC123
          PincodeEnabled:
            type: string
            example: ABC123
          passkey:
            type: string
            example: ABC123
          startIP:
            type: string
            example: ABC123
          endIP:
            type: string
            example: ABC123
      WirelessConfig:
        type: object
        properties:
          essid:
            type: string
            example: ABC123
          password:
            type: string
            example: ABC123
          autoconnect:
            type: string
            example: ABC123
      RegionConfig:
        type: object
        properties:
          RFCountry:
            type: string
            example: ABC123
          RFRegulatory:
            type: string
            example: ABC123
          RFScanMode:
            type: string
            example: ABC123
          LBTEnable:
            type: string
            example: ABC123
          ChannelData:
            type: string
            example: ABC123
      SnmpConfig:
        type: object
        properties:
          snmpVersion:
            type: string
            example: ABC123
          heartbeat:
            type: string
            example: ABC123
      SyslogConfig:
        type: object
        properties:
          RemoteIp:
            type: string
            example: ABC123
          RemotePort:
            type: string
            example: ABC123
          LogMinSeverity:
            type: string
            example: ABC123
          ApplyFilter:
            type: string
            example: ABC123
          MinimumSeverity:
            type: string
            example: ABC123
          ProcessFilter:
            type: string
            example: ABC123
      UserList:
        type: object
        properties:
          User:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                  example: ABC123
                PSWD:
                  type: string
                  example: ABC123
      IPReader:
        type: object
        properties:
          name:
            type: string
            example: ABC123
          desc:
            type: string
            example: ABC123
          flags:
            type: string
            example: ABC123
          MonoStatic:
            type: string
            example: ABC123
          CheckAntenna:
            type: string
            example: ABC123
          gpiDebounceTime:
            type: string
            example: ABC123
          gpioMapping:
            type: string
            example: ABC123
          idleModeTimeOut:
            type: string
            example: ABC123
          diagMode:
            type: string
            example: ABC123
          extDiagMode:
            type: string
            example: ABC123
          contact:
            type: string
            example: ABC123
          PowerNegotiation:
            type: string
            example: ABC123
          PowerNegotiationProtocol:
            type: string
            example: ABC123
          allowGuestLogin:
            type: string
            example: ABC123
          ReadPoint:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                  example: ABC123
                flags:
                  type: string
                  example: ABC123
                CableLossPerHundredFt:
                  type: string
                  example: ABC123
                CableLength:
                  type: string
                  example: ABC123
      SerialPortConf:
        type: object
        properties:
          Mode:
            type: string
            example: ABC123
          Baudrate:
            type: string
            example: ABC123
          Databits:
            type: string
            example: ABC123
          Parity:
            type: string
            example: ABC123
          Stopbits:
            type: string
            example: ABC123
          Flowcontrol:
            type: string
            example: ABC123
          TagMetaData:
            type: string
            example: ABC123
          InventoryControl:
            type: string
            example: ABC123
  RadioProfileData:
    type: object
    properties:
      RadioRegisterData:
        type: object
        properties:
          Address:
            type: string
            example: ABC123
          Data:
            type: string
            example: ABC123
  CustomProfileData:
    type: object
    properties:
      ForceEAPMode:
        type: string
        example: ABC123
      FIPS_MODE_ENABLED:
        type: string
        example: ABC123
      MaxNumberOfTagsBuffered:
        type: string
        example: ABC123
