openapi: 3.0.0
info:
  title: person
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000/person'
paths:
  /person:
    parameters: []
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    type: string
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
        description: ''
components:
  schemas: {}
  securitySchemes: {}
